sudo: false
language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
    - "$HOME/.cache"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0aa9a5b8a28b7ac1026
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always


deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - mvn clean test jacoco:report coveralls:report
