sudo: false
language: java
dist: trusty
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
    - "$HOME/.cache"

notifications:
  webhooks:
    urls:
      - "$JPGM_GITTER_WEBHOOK_URL"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true

after_success:
  - mvn clean test jacoco:report coveralls:report
